// Types for worldwide corona details
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_INIT = "GET_USER_LIST_INIT";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR";
export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE";
export const GET_USER_LIST_COMPLETED = "GET_USER_LIST_COMPLETED";
